//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsCalculatorClient.ServiceReferenceCalculator {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceCalculator.WebServiceCalculatorSoap")]
    public interface WebServiceCalculatorSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WindowsFormsCalculatorClient.ServiceReferenceCalculator.HelloWorldResponse HelloWorld(WindowsFormsCalculatorClient.ServiceReferenceCalculator.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsCalculatorClient.ServiceReferenceCalculator.HelloWorldResponse> HelloWorldAsync(WindowsFormsCalculatorClient.ServiceReferenceCalculator.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        int Add(int n1, int n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddAsync(int n1, int n2);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsCalculatorClient.ServiceReferenceCalculator.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WindowsFormsCalculatorClient.ServiceReferenceCalculator.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsCalculatorClient.ServiceReferenceCalculator.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WindowsFormsCalculatorClient.ServiceReferenceCalculator.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceCalculatorSoapChannel : WindowsFormsCalculatorClient.ServiceReferenceCalculator.WebServiceCalculatorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceCalculatorSoapClient : System.ServiceModel.ClientBase<WindowsFormsCalculatorClient.ServiceReferenceCalculator.WebServiceCalculatorSoap>, WindowsFormsCalculatorClient.ServiceReferenceCalculator.WebServiceCalculatorSoap {
        
        public WebServiceCalculatorSoapClient() {
        }
        
        public WebServiceCalculatorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceCalculatorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceCalculatorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceCalculatorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsCalculatorClient.ServiceReferenceCalculator.HelloWorldResponse WindowsFormsCalculatorClient.ServiceReferenceCalculator.WebServiceCalculatorSoap.HelloWorld(WindowsFormsCalculatorClient.ServiceReferenceCalculator.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WindowsFormsCalculatorClient.ServiceReferenceCalculator.HelloWorldRequest inValue = new WindowsFormsCalculatorClient.ServiceReferenceCalculator.HelloWorldRequest();
            inValue.Body = new WindowsFormsCalculatorClient.ServiceReferenceCalculator.HelloWorldRequestBody();
            WindowsFormsCalculatorClient.ServiceReferenceCalculator.HelloWorldResponse retVal = ((WindowsFormsCalculatorClient.ServiceReferenceCalculator.WebServiceCalculatorSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsCalculatorClient.ServiceReferenceCalculator.HelloWorldResponse> WindowsFormsCalculatorClient.ServiceReferenceCalculator.WebServiceCalculatorSoap.HelloWorldAsync(WindowsFormsCalculatorClient.ServiceReferenceCalculator.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsCalculatorClient.ServiceReferenceCalculator.HelloWorldResponse> HelloWorldAsync() {
            WindowsFormsCalculatorClient.ServiceReferenceCalculator.HelloWorldRequest inValue = new WindowsFormsCalculatorClient.ServiceReferenceCalculator.HelloWorldRequest();
            inValue.Body = new WindowsFormsCalculatorClient.ServiceReferenceCalculator.HelloWorldRequestBody();
            return ((WindowsFormsCalculatorClient.ServiceReferenceCalculator.WebServiceCalculatorSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public int Add(int n1, int n2) {
            return base.Channel.Add(n1, n2);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int n1, int n2) {
            return base.Channel.AddAsync(n1, n2);
        }
    }
}
