//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Controller.ServiceReferenceLogin {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int UidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        private int UserLevelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Uid {
            get {
                return this.UidField;
            }
            set {
                if ((this.UidField.Equals(value) != true)) {
                    this.UidField = value;
                    this.RaisePropertyChanged("Uid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int UserLevel {
            get {
                return this.UserLevelField;
            }
            set {
                if ((this.UserLevelField.Equals(value) != true)) {
                    this.UserLevelField = value;
                    this.RaisePropertyChanged("UserLevel");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceLogin.WebServiceLibrarySoap")]
    public interface WebServiceLibrarySoap {
        
        // CODEGEN: Generating message contract since element name sUserName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValideLogin", ReplyAction="*")]
        Controller.ServiceReferenceLogin.ValideLoginResponse ValideLogin(Controller.ServiceReferenceLogin.ValideLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValideLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<Controller.ServiceReferenceLogin.ValideLoginResponse> ValideLoginAsync(Controller.ServiceReferenceLogin.ValideLoginRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllUsersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllUsers", ReplyAction="*")]
        Controller.ServiceReferenceLogin.GetAllUsersResponse GetAllUsers(Controller.ServiceReferenceLogin.GetAllUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<Controller.ServiceReferenceLogin.GetAllUsersResponse> GetAllUsersAsync(Controller.ServiceReferenceLogin.GetAllUsersRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertNewUser", ReplyAction="*")]
        Controller.ServiceReferenceLogin.InsertNewUserResponse InsertNewUser(Controller.ServiceReferenceLogin.InsertNewUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertNewUser", ReplyAction="*")]
        System.Threading.Tasks.Task<Controller.ServiceReferenceLogin.InsertNewUserResponse> InsertNewUserAsync(Controller.ServiceReferenceLogin.InsertNewUserRequest request);
        
        // CODEGEN: Generating message contract since element name updatedUserName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateUser", ReplyAction="*")]
        Controller.ServiceReferenceLogin.UpdateUserResponse UpdateUser(Controller.ServiceReferenceLogin.UpdateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<Controller.ServiceReferenceLogin.UpdateUserResponse> UpdateUserAsync(Controller.ServiceReferenceLogin.UpdateUserRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteUser", ReplyAction="*")]
        Controller.ServiceReferenceLogin.DeleteUserResponse DeleteUser(Controller.ServiceReferenceLogin.DeleteUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteUser", ReplyAction="*")]
        System.Threading.Tasks.Task<Controller.ServiceReferenceLogin.DeleteUserResponse> DeleteUserAsync(Controller.ServiceReferenceLogin.DeleteUserRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValideLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValideLogin", Namespace="http://tempuri.org/", Order=0)]
        public Controller.ServiceReferenceLogin.ValideLoginRequestBody Body;
        
        public ValideLoginRequest() {
        }
        
        public ValideLoginRequest(Controller.ServiceReferenceLogin.ValideLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValideLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sPassword;
        
        public ValideLoginRequestBody() {
        }
        
        public ValideLoginRequestBody(string sUserName, string sPassword) {
            this.sUserName = sUserName;
            this.sPassword = sPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValideLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValideLoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public Controller.ServiceReferenceLogin.ValideLoginResponseBody Body;
        
        public ValideLoginResponse() {
        }
        
        public ValideLoginResponse(Controller.ServiceReferenceLogin.ValideLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValideLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Controller.ServiceReferenceLogin.User ValideLoginResult;
        
        public ValideLoginResponseBody() {
        }
        
        public ValideLoginResponseBody(Controller.ServiceReferenceLogin.User ValideLoginResult) {
            this.ValideLoginResult = ValideLoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllUsers", Namespace="http://tempuri.org/", Order=0)]
        public Controller.ServiceReferenceLogin.GetAllUsersRequestBody Body;
        
        public GetAllUsersRequest() {
        }
        
        public GetAllUsersRequest(Controller.ServiceReferenceLogin.GetAllUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllUsersRequestBody {
        
        public GetAllUsersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllUsersResponse", Namespace="http://tempuri.org/", Order=0)]
        public Controller.ServiceReferenceLogin.GetAllUsersResponseBody Body;
        
        public GetAllUsersResponse() {
        }
        
        public GetAllUsersResponse(Controller.ServiceReferenceLogin.GetAllUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllUsersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Controller.ServiceReferenceLogin.User[] GetAllUsersResult;
        
        public GetAllUsersResponseBody() {
        }
        
        public GetAllUsersResponseBody(Controller.ServiceReferenceLogin.User[] GetAllUsersResult) {
            this.GetAllUsersResult = GetAllUsersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertNewUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertNewUser", Namespace="http://tempuri.org/", Order=0)]
        public Controller.ServiceReferenceLogin.InsertNewUserRequestBody Body;
        
        public InsertNewUserRequest() {
        }
        
        public InsertNewUserRequest(Controller.ServiceReferenceLogin.InsertNewUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertNewUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int userLevel;
        
        public InsertNewUserRequestBody() {
        }
        
        public InsertNewUserRequestBody(string userName, string password, int userLevel) {
            this.userName = userName;
            this.password = password;
            this.userLevel = userLevel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertNewUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertNewUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public Controller.ServiceReferenceLogin.InsertNewUserResponseBody Body;
        
        public InsertNewUserResponse() {
        }
        
        public InsertNewUserResponse(Controller.ServiceReferenceLogin.InsertNewUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertNewUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int InsertNewUserResult;
        
        public InsertNewUserResponseBody() {
        }
        
        public InsertNewUserResponseBody(int InsertNewUserResult) {
            this.InsertNewUserResult = InsertNewUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUser", Namespace="http://tempuri.org/", Order=0)]
        public Controller.ServiceReferenceLogin.UpdateUserRequestBody Body;
        
        public UpdateUserRequest() {
        }
        
        public UpdateUserRequest(Controller.ServiceReferenceLogin.UpdateUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string updatedUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string updatedPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int updatedUserLevel;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string originalUserName;
        
        public UpdateUserRequestBody() {
        }
        
        public UpdateUserRequestBody(string updatedUserName, string updatedPassword, int updatedUserLevel, string originalUserName) {
            this.updatedUserName = updatedUserName;
            this.updatedPassword = updatedPassword;
            this.updatedUserLevel = updatedUserLevel;
            this.originalUserName = originalUserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public Controller.ServiceReferenceLogin.UpdateUserResponseBody Body;
        
        public UpdateUserResponse() {
        }
        
        public UpdateUserResponse(Controller.ServiceReferenceLogin.UpdateUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdateUserResult;
        
        public UpdateUserResponseBody() {
        }
        
        public UpdateUserResponseBody(int UpdateUserResult) {
            this.UpdateUserResult = UpdateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteUser", Namespace="http://tempuri.org/", Order=0)]
        public Controller.ServiceReferenceLogin.DeleteUserRequestBody Body;
        
        public DeleteUserRequest() {
        }
        
        public DeleteUserRequest(Controller.ServiceReferenceLogin.DeleteUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        public DeleteUserRequestBody() {
        }
        
        public DeleteUserRequestBody(string userName) {
            this.userName = userName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public Controller.ServiceReferenceLogin.DeleteUserResponseBody Body;
        
        public DeleteUserResponse() {
        }
        
        public DeleteUserResponse(Controller.ServiceReferenceLogin.DeleteUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DeleteUserResult;
        
        public DeleteUserResponseBody() {
        }
        
        public DeleteUserResponseBody(int DeleteUserResult) {
            this.DeleteUserResult = DeleteUserResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceLibrarySoapChannel : Controller.ServiceReferenceLogin.WebServiceLibrarySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceLibrarySoapClient : System.ServiceModel.ClientBase<Controller.ServiceReferenceLogin.WebServiceLibrarySoap>, Controller.ServiceReferenceLogin.WebServiceLibrarySoap {
        
        public WebServiceLibrarySoapClient() {
        }
        
        public WebServiceLibrarySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceLibrarySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceLibrarySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceLibrarySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Controller.ServiceReferenceLogin.ValideLoginResponse Controller.ServiceReferenceLogin.WebServiceLibrarySoap.ValideLogin(Controller.ServiceReferenceLogin.ValideLoginRequest request) {
            return base.Channel.ValideLogin(request);
        }
        
        public Controller.ServiceReferenceLogin.User ValideLogin(string sUserName, string sPassword) {
            Controller.ServiceReferenceLogin.ValideLoginRequest inValue = new Controller.ServiceReferenceLogin.ValideLoginRequest();
            inValue.Body = new Controller.ServiceReferenceLogin.ValideLoginRequestBody();
            inValue.Body.sUserName = sUserName;
            inValue.Body.sPassword = sPassword;
            Controller.ServiceReferenceLogin.ValideLoginResponse retVal = ((Controller.ServiceReferenceLogin.WebServiceLibrarySoap)(this)).ValideLogin(inValue);
            return retVal.Body.ValideLoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Controller.ServiceReferenceLogin.ValideLoginResponse> Controller.ServiceReferenceLogin.WebServiceLibrarySoap.ValideLoginAsync(Controller.ServiceReferenceLogin.ValideLoginRequest request) {
            return base.Channel.ValideLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<Controller.ServiceReferenceLogin.ValideLoginResponse> ValideLoginAsync(string sUserName, string sPassword) {
            Controller.ServiceReferenceLogin.ValideLoginRequest inValue = new Controller.ServiceReferenceLogin.ValideLoginRequest();
            inValue.Body = new Controller.ServiceReferenceLogin.ValideLoginRequestBody();
            inValue.Body.sUserName = sUserName;
            inValue.Body.sPassword = sPassword;
            return ((Controller.ServiceReferenceLogin.WebServiceLibrarySoap)(this)).ValideLoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Controller.ServiceReferenceLogin.GetAllUsersResponse Controller.ServiceReferenceLogin.WebServiceLibrarySoap.GetAllUsers(Controller.ServiceReferenceLogin.GetAllUsersRequest request) {
            return base.Channel.GetAllUsers(request);
        }
        
        public Controller.ServiceReferenceLogin.User[] GetAllUsers() {
            Controller.ServiceReferenceLogin.GetAllUsersRequest inValue = new Controller.ServiceReferenceLogin.GetAllUsersRequest();
            inValue.Body = new Controller.ServiceReferenceLogin.GetAllUsersRequestBody();
            Controller.ServiceReferenceLogin.GetAllUsersResponse retVal = ((Controller.ServiceReferenceLogin.WebServiceLibrarySoap)(this)).GetAllUsers(inValue);
            return retVal.Body.GetAllUsersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Controller.ServiceReferenceLogin.GetAllUsersResponse> Controller.ServiceReferenceLogin.WebServiceLibrarySoap.GetAllUsersAsync(Controller.ServiceReferenceLogin.GetAllUsersRequest request) {
            return base.Channel.GetAllUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<Controller.ServiceReferenceLogin.GetAllUsersResponse> GetAllUsersAsync() {
            Controller.ServiceReferenceLogin.GetAllUsersRequest inValue = new Controller.ServiceReferenceLogin.GetAllUsersRequest();
            inValue.Body = new Controller.ServiceReferenceLogin.GetAllUsersRequestBody();
            return ((Controller.ServiceReferenceLogin.WebServiceLibrarySoap)(this)).GetAllUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Controller.ServiceReferenceLogin.InsertNewUserResponse Controller.ServiceReferenceLogin.WebServiceLibrarySoap.InsertNewUser(Controller.ServiceReferenceLogin.InsertNewUserRequest request) {
            return base.Channel.InsertNewUser(request);
        }
        
        public int InsertNewUser(string userName, string password, int userLevel) {
            Controller.ServiceReferenceLogin.InsertNewUserRequest inValue = new Controller.ServiceReferenceLogin.InsertNewUserRequest();
            inValue.Body = new Controller.ServiceReferenceLogin.InsertNewUserRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.userLevel = userLevel;
            Controller.ServiceReferenceLogin.InsertNewUserResponse retVal = ((Controller.ServiceReferenceLogin.WebServiceLibrarySoap)(this)).InsertNewUser(inValue);
            return retVal.Body.InsertNewUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Controller.ServiceReferenceLogin.InsertNewUserResponse> Controller.ServiceReferenceLogin.WebServiceLibrarySoap.InsertNewUserAsync(Controller.ServiceReferenceLogin.InsertNewUserRequest request) {
            return base.Channel.InsertNewUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Controller.ServiceReferenceLogin.InsertNewUserResponse> InsertNewUserAsync(string userName, string password, int userLevel) {
            Controller.ServiceReferenceLogin.InsertNewUserRequest inValue = new Controller.ServiceReferenceLogin.InsertNewUserRequest();
            inValue.Body = new Controller.ServiceReferenceLogin.InsertNewUserRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.userLevel = userLevel;
            return ((Controller.ServiceReferenceLogin.WebServiceLibrarySoap)(this)).InsertNewUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Controller.ServiceReferenceLogin.UpdateUserResponse Controller.ServiceReferenceLogin.WebServiceLibrarySoap.UpdateUser(Controller.ServiceReferenceLogin.UpdateUserRequest request) {
            return base.Channel.UpdateUser(request);
        }
        
        public int UpdateUser(string updatedUserName, string updatedPassword, int updatedUserLevel, string originalUserName) {
            Controller.ServiceReferenceLogin.UpdateUserRequest inValue = new Controller.ServiceReferenceLogin.UpdateUserRequest();
            inValue.Body = new Controller.ServiceReferenceLogin.UpdateUserRequestBody();
            inValue.Body.updatedUserName = updatedUserName;
            inValue.Body.updatedPassword = updatedPassword;
            inValue.Body.updatedUserLevel = updatedUserLevel;
            inValue.Body.originalUserName = originalUserName;
            Controller.ServiceReferenceLogin.UpdateUserResponse retVal = ((Controller.ServiceReferenceLogin.WebServiceLibrarySoap)(this)).UpdateUser(inValue);
            return retVal.Body.UpdateUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Controller.ServiceReferenceLogin.UpdateUserResponse> Controller.ServiceReferenceLogin.WebServiceLibrarySoap.UpdateUserAsync(Controller.ServiceReferenceLogin.UpdateUserRequest request) {
            return base.Channel.UpdateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Controller.ServiceReferenceLogin.UpdateUserResponse> UpdateUserAsync(string updatedUserName, string updatedPassword, int updatedUserLevel, string originalUserName) {
            Controller.ServiceReferenceLogin.UpdateUserRequest inValue = new Controller.ServiceReferenceLogin.UpdateUserRequest();
            inValue.Body = new Controller.ServiceReferenceLogin.UpdateUserRequestBody();
            inValue.Body.updatedUserName = updatedUserName;
            inValue.Body.updatedPassword = updatedPassword;
            inValue.Body.updatedUserLevel = updatedUserLevel;
            inValue.Body.originalUserName = originalUserName;
            return ((Controller.ServiceReferenceLogin.WebServiceLibrarySoap)(this)).UpdateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Controller.ServiceReferenceLogin.DeleteUserResponse Controller.ServiceReferenceLogin.WebServiceLibrarySoap.DeleteUser(Controller.ServiceReferenceLogin.DeleteUserRequest request) {
            return base.Channel.DeleteUser(request);
        }
        
        public int DeleteUser(string userName) {
            Controller.ServiceReferenceLogin.DeleteUserRequest inValue = new Controller.ServiceReferenceLogin.DeleteUserRequest();
            inValue.Body = new Controller.ServiceReferenceLogin.DeleteUserRequestBody();
            inValue.Body.userName = userName;
            Controller.ServiceReferenceLogin.DeleteUserResponse retVal = ((Controller.ServiceReferenceLogin.WebServiceLibrarySoap)(this)).DeleteUser(inValue);
            return retVal.Body.DeleteUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Controller.ServiceReferenceLogin.DeleteUserResponse> Controller.ServiceReferenceLogin.WebServiceLibrarySoap.DeleteUserAsync(Controller.ServiceReferenceLogin.DeleteUserRequest request) {
            return base.Channel.DeleteUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Controller.ServiceReferenceLogin.DeleteUserResponse> DeleteUserAsync(string userName) {
            Controller.ServiceReferenceLogin.DeleteUserRequest inValue = new Controller.ServiceReferenceLogin.DeleteUserRequest();
            inValue.Body = new Controller.ServiceReferenceLogin.DeleteUserRequestBody();
            inValue.Body.userName = userName;
            return ((Controller.ServiceReferenceLogin.WebServiceLibrarySoap)(this)).DeleteUserAsync(inValue);
        }
    }
}
