//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Controller.ServiceReferenceCategory {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Cid {
            get {
                return this.CidField;
            }
            set {
                if ((this.CidField.Equals(value) != true)) {
                    this.CidField = value;
                    this.RaisePropertyChanged("Cid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CategoryName {
            get {
                return this.CategoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryNameField, value) != true)) {
                    this.CategoryNameField = value;
                    this.RaisePropertyChanged("CategoryName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceCategory.WebServiceCategoryasmxSoap")]
    public interface WebServiceCategoryasmxSoap {
        
        // CODEGEN: Generating message contract since element name ShowCategoryResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowCategory", ReplyAction="*")]
        Controller.ServiceReferenceCategory.ShowCategoryResponse ShowCategory(Controller.ServiceReferenceCategory.ShowCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<Controller.ServiceReferenceCategory.ShowCategoryResponse> ShowCategoryAsync(Controller.ServiceReferenceCategory.ShowCategoryRequest request);
        
        // CODEGEN: Generating message contract since element name categoryNames from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveCategory", ReplyAction="*")]
        Controller.ServiceReferenceCategory.SaveCategoryResponse SaveCategory(Controller.ServiceReferenceCategory.SaveCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<Controller.ServiceReferenceCategory.SaveCategoryResponse> SaveCategoryAsync(Controller.ServiceReferenceCategory.SaveCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteCategory", ReplyAction="*")]
        int DeleteCategory(int cid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<int> DeleteCategoryAsync(int cid);
        
        // CODEGEN: Generating message contract since element name originalNames from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCategory", ReplyAction="*")]
        Controller.ServiceReferenceCategory.UpdateCategoryResponse UpdateCategory(Controller.ServiceReferenceCategory.UpdateCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<Controller.ServiceReferenceCategory.UpdateCategoryResponse> UpdateCategoryAsync(Controller.ServiceReferenceCategory.UpdateCategoryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowCategoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowCategory", Namespace="http://tempuri.org/", Order=0)]
        public Controller.ServiceReferenceCategory.ShowCategoryRequestBody Body;
        
        public ShowCategoryRequest() {
        }
        
        public ShowCategoryRequest(Controller.ServiceReferenceCategory.ShowCategoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ShowCategoryRequestBody {
        
        public ShowCategoryRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowCategoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowCategoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public Controller.ServiceReferenceCategory.ShowCategoryResponseBody Body;
        
        public ShowCategoryResponse() {
        }
        
        public ShowCategoryResponse(Controller.ServiceReferenceCategory.ShowCategoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ShowCategoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Controller.ServiceReferenceCategory.Category[] ShowCategoryResult;
        
        public ShowCategoryResponseBody() {
        }
        
        public ShowCategoryResponseBody(Controller.ServiceReferenceCategory.Category[] ShowCategoryResult) {
            this.ShowCategoryResult = ShowCategoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveCategoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveCategory", Namespace="http://tempuri.org/", Order=0)]
        public Controller.ServiceReferenceCategory.SaveCategoryRequestBody Body;
        
        public SaveCategoryRequest() {
        }
        
        public SaveCategoryRequest(Controller.ServiceReferenceCategory.SaveCategoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveCategoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string categoryNames;
        
        public SaveCategoryRequestBody() {
        }
        
        public SaveCategoryRequestBody(string categoryNames) {
            this.categoryNames = categoryNames;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveCategoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveCategoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public Controller.ServiceReferenceCategory.SaveCategoryResponseBody Body;
        
        public SaveCategoryResponse() {
        }
        
        public SaveCategoryResponse(Controller.ServiceReferenceCategory.SaveCategoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveCategoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SaveCategoryResult;
        
        public SaveCategoryResponseBody() {
        }
        
        public SaveCategoryResponseBody(int SaveCategoryResult) {
            this.SaveCategoryResult = SaveCategoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCategoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCategory", Namespace="http://tempuri.org/", Order=0)]
        public Controller.ServiceReferenceCategory.UpdateCategoryRequestBody Body;
        
        public UpdateCategoryRequest() {
        }
        
        public UpdateCategoryRequest(Controller.ServiceReferenceCategory.UpdateCategoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateCategoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string originalNames;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int originalCid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string newName;
        
        public UpdateCategoryRequestBody() {
        }
        
        public UpdateCategoryRequestBody(string originalNames, int originalCid, string newName) {
            this.originalNames = originalNames;
            this.originalCid = originalCid;
            this.newName = newName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCategoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCategoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public Controller.ServiceReferenceCategory.UpdateCategoryResponseBody Body;
        
        public UpdateCategoryResponse() {
        }
        
        public UpdateCategoryResponse(Controller.ServiceReferenceCategory.UpdateCategoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateCategoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdateCategoryResult;
        
        public UpdateCategoryResponseBody() {
        }
        
        public UpdateCategoryResponseBody(int UpdateCategoryResult) {
            this.UpdateCategoryResult = UpdateCategoryResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceCategoryasmxSoapChannel : Controller.ServiceReferenceCategory.WebServiceCategoryasmxSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceCategoryasmxSoapClient : System.ServiceModel.ClientBase<Controller.ServiceReferenceCategory.WebServiceCategoryasmxSoap>, Controller.ServiceReferenceCategory.WebServiceCategoryasmxSoap {
        
        public WebServiceCategoryasmxSoapClient() {
        }
        
        public WebServiceCategoryasmxSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceCategoryasmxSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceCategoryasmxSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceCategoryasmxSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Controller.ServiceReferenceCategory.ShowCategoryResponse Controller.ServiceReferenceCategory.WebServiceCategoryasmxSoap.ShowCategory(Controller.ServiceReferenceCategory.ShowCategoryRequest request) {
            return base.Channel.ShowCategory(request);
        }
        
        public Controller.ServiceReferenceCategory.Category[] ShowCategory() {
            Controller.ServiceReferenceCategory.ShowCategoryRequest inValue = new Controller.ServiceReferenceCategory.ShowCategoryRequest();
            inValue.Body = new Controller.ServiceReferenceCategory.ShowCategoryRequestBody();
            Controller.ServiceReferenceCategory.ShowCategoryResponse retVal = ((Controller.ServiceReferenceCategory.WebServiceCategoryasmxSoap)(this)).ShowCategory(inValue);
            return retVal.Body.ShowCategoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Controller.ServiceReferenceCategory.ShowCategoryResponse> Controller.ServiceReferenceCategory.WebServiceCategoryasmxSoap.ShowCategoryAsync(Controller.ServiceReferenceCategory.ShowCategoryRequest request) {
            return base.Channel.ShowCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<Controller.ServiceReferenceCategory.ShowCategoryResponse> ShowCategoryAsync() {
            Controller.ServiceReferenceCategory.ShowCategoryRequest inValue = new Controller.ServiceReferenceCategory.ShowCategoryRequest();
            inValue.Body = new Controller.ServiceReferenceCategory.ShowCategoryRequestBody();
            return ((Controller.ServiceReferenceCategory.WebServiceCategoryasmxSoap)(this)).ShowCategoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Controller.ServiceReferenceCategory.SaveCategoryResponse Controller.ServiceReferenceCategory.WebServiceCategoryasmxSoap.SaveCategory(Controller.ServiceReferenceCategory.SaveCategoryRequest request) {
            return base.Channel.SaveCategory(request);
        }
        
        public int SaveCategory(string categoryNames) {
            Controller.ServiceReferenceCategory.SaveCategoryRequest inValue = new Controller.ServiceReferenceCategory.SaveCategoryRequest();
            inValue.Body = new Controller.ServiceReferenceCategory.SaveCategoryRequestBody();
            inValue.Body.categoryNames = categoryNames;
            Controller.ServiceReferenceCategory.SaveCategoryResponse retVal = ((Controller.ServiceReferenceCategory.WebServiceCategoryasmxSoap)(this)).SaveCategory(inValue);
            return retVal.Body.SaveCategoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Controller.ServiceReferenceCategory.SaveCategoryResponse> Controller.ServiceReferenceCategory.WebServiceCategoryasmxSoap.SaveCategoryAsync(Controller.ServiceReferenceCategory.SaveCategoryRequest request) {
            return base.Channel.SaveCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<Controller.ServiceReferenceCategory.SaveCategoryResponse> SaveCategoryAsync(string categoryNames) {
            Controller.ServiceReferenceCategory.SaveCategoryRequest inValue = new Controller.ServiceReferenceCategory.SaveCategoryRequest();
            inValue.Body = new Controller.ServiceReferenceCategory.SaveCategoryRequestBody();
            inValue.Body.categoryNames = categoryNames;
            return ((Controller.ServiceReferenceCategory.WebServiceCategoryasmxSoap)(this)).SaveCategoryAsync(inValue);
        }
        
        public int DeleteCategory(int cid) {
            return base.Channel.DeleteCategory(cid);
        }
        
        public System.Threading.Tasks.Task<int> DeleteCategoryAsync(int cid) {
            return base.Channel.DeleteCategoryAsync(cid);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Controller.ServiceReferenceCategory.UpdateCategoryResponse Controller.ServiceReferenceCategory.WebServiceCategoryasmxSoap.UpdateCategory(Controller.ServiceReferenceCategory.UpdateCategoryRequest request) {
            return base.Channel.UpdateCategory(request);
        }
        
        public int UpdateCategory(string originalNames, int originalCid, string newName) {
            Controller.ServiceReferenceCategory.UpdateCategoryRequest inValue = new Controller.ServiceReferenceCategory.UpdateCategoryRequest();
            inValue.Body = new Controller.ServiceReferenceCategory.UpdateCategoryRequestBody();
            inValue.Body.originalNames = originalNames;
            inValue.Body.originalCid = originalCid;
            inValue.Body.newName = newName;
            Controller.ServiceReferenceCategory.UpdateCategoryResponse retVal = ((Controller.ServiceReferenceCategory.WebServiceCategoryasmxSoap)(this)).UpdateCategory(inValue);
            return retVal.Body.UpdateCategoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Controller.ServiceReferenceCategory.UpdateCategoryResponse> Controller.ServiceReferenceCategory.WebServiceCategoryasmxSoap.UpdateCategoryAsync(Controller.ServiceReferenceCategory.UpdateCategoryRequest request) {
            return base.Channel.UpdateCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<Controller.ServiceReferenceCategory.UpdateCategoryResponse> UpdateCategoryAsync(string originalNames, int originalCid, string newName) {
            Controller.ServiceReferenceCategory.UpdateCategoryRequest inValue = new Controller.ServiceReferenceCategory.UpdateCategoryRequest();
            inValue.Body = new Controller.ServiceReferenceCategory.UpdateCategoryRequestBody();
            inValue.Body.originalNames = originalNames;
            inValue.Body.originalCid = originalCid;
            inValue.Body.newName = newName;
            return ((Controller.ServiceReferenceCategory.WebServiceCategoryasmxSoap)(this)).UpdateCategoryAsync(inValue);
        }
    }
}
