//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Controller.ServiceReferenceBooks {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Books", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Books : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsbnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BookNameField;
        
        private int AuthorField;
        
        private int CategoryField;
        
        private int LanguageField;
        
        private int PublishYearField;
        
        private int PagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PublisherField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Isbn {
            get {
                return this.IsbnField;
            }
            set {
                if ((object.ReferenceEquals(this.IsbnField, value) != true)) {
                    this.IsbnField = value;
                    this.RaisePropertyChanged("Isbn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BookName {
            get {
                return this.BookNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BookNameField, value) != true)) {
                    this.BookNameField = value;
                    this.RaisePropertyChanged("BookName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((this.AuthorField.Equals(value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((this.CategoryField.Equals(value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((this.LanguageField.Equals(value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int PublishYear {
            get {
                return this.PublishYearField;
            }
            set {
                if ((this.PublishYearField.Equals(value) != true)) {
                    this.PublishYearField = value;
                    this.RaisePropertyChanged("PublishYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int Pages {
            get {
                return this.PagesField;
            }
            set {
                if ((this.PagesField.Equals(value) != true)) {
                    this.PagesField = value;
                    this.RaisePropertyChanged("Pages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Publisher {
            get {
                return this.PublisherField;
            }
            set {
                if ((object.ReferenceEquals(this.PublisherField, value) != true)) {
                    this.PublisherField = value;
                    this.RaisePropertyChanged("Publisher");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceBooks.WebServiceBooksSoap")]
    public interface WebServiceBooksSoap {
        
        // CODEGEN: Generating message contract since element name GetAllBooksResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllBooks", ReplyAction="*")]
        Controller.ServiceReferenceBooks.GetAllBooksResponse GetAllBooks(Controller.ServiceReferenceBooks.GetAllBooksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllBooks", ReplyAction="*")]
        System.Threading.Tasks.Task<Controller.ServiceReferenceBooks.GetAllBooksResponse> GetAllBooksAsync(Controller.ServiceReferenceBooks.GetAllBooksRequest request);
        
        // CODEGEN: Generating message contract since element name booksName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchBook", ReplyAction="*")]
        Controller.ServiceReferenceBooks.SearchBookResponse SearchBook(Controller.ServiceReferenceBooks.SearchBookRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchBook", ReplyAction="*")]
        System.Threading.Tasks.Task<Controller.ServiceReferenceBooks.SearchBookResponse> SearchBookAsync(Controller.ServiceReferenceBooks.SearchBookRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllBooksRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllBooks", Namespace="http://tempuri.org/", Order=0)]
        public Controller.ServiceReferenceBooks.GetAllBooksRequestBody Body;
        
        public GetAllBooksRequest() {
        }
        
        public GetAllBooksRequest(Controller.ServiceReferenceBooks.GetAllBooksRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllBooksRequestBody {
        
        public GetAllBooksRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllBooksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllBooksResponse", Namespace="http://tempuri.org/", Order=0)]
        public Controller.ServiceReferenceBooks.GetAllBooksResponseBody Body;
        
        public GetAllBooksResponse() {
        }
        
        public GetAllBooksResponse(Controller.ServiceReferenceBooks.GetAllBooksResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllBooksResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Controller.ServiceReferenceBooks.Books[] GetAllBooksResult;
        
        public GetAllBooksResponseBody() {
        }
        
        public GetAllBooksResponseBody(Controller.ServiceReferenceBooks.Books[] GetAllBooksResult) {
            this.GetAllBooksResult = GetAllBooksResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchBookRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchBook", Namespace="http://tempuri.org/", Order=0)]
        public Controller.ServiceReferenceBooks.SearchBookRequestBody Body;
        
        public SearchBookRequest() {
        }
        
        public SearchBookRequest(Controller.ServiceReferenceBooks.SearchBookRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchBookRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string booksName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int publishedYear;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string publisherName;
        
        public SearchBookRequestBody() {
        }
        
        public SearchBookRequestBody(string booksName, int publishedYear, string publisherName) {
            this.booksName = booksName;
            this.publishedYear = publishedYear;
            this.publisherName = publisherName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchBookResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchBookResponse", Namespace="http://tempuri.org/", Order=0)]
        public Controller.ServiceReferenceBooks.SearchBookResponseBody Body;
        
        public SearchBookResponse() {
        }
        
        public SearchBookResponse(Controller.ServiceReferenceBooks.SearchBookResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchBookResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Controller.ServiceReferenceBooks.Books[] SearchBookResult;
        
        public SearchBookResponseBody() {
        }
        
        public SearchBookResponseBody(Controller.ServiceReferenceBooks.Books[] SearchBookResult) {
            this.SearchBookResult = SearchBookResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceBooksSoapChannel : Controller.ServiceReferenceBooks.WebServiceBooksSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceBooksSoapClient : System.ServiceModel.ClientBase<Controller.ServiceReferenceBooks.WebServiceBooksSoap>, Controller.ServiceReferenceBooks.WebServiceBooksSoap {
        
        public WebServiceBooksSoapClient() {
        }
        
        public WebServiceBooksSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceBooksSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceBooksSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceBooksSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Controller.ServiceReferenceBooks.GetAllBooksResponse Controller.ServiceReferenceBooks.WebServiceBooksSoap.GetAllBooks(Controller.ServiceReferenceBooks.GetAllBooksRequest request) {
            return base.Channel.GetAllBooks(request);
        }
        
        public Controller.ServiceReferenceBooks.Books[] GetAllBooks() {
            Controller.ServiceReferenceBooks.GetAllBooksRequest inValue = new Controller.ServiceReferenceBooks.GetAllBooksRequest();
            inValue.Body = new Controller.ServiceReferenceBooks.GetAllBooksRequestBody();
            Controller.ServiceReferenceBooks.GetAllBooksResponse retVal = ((Controller.ServiceReferenceBooks.WebServiceBooksSoap)(this)).GetAllBooks(inValue);
            return retVal.Body.GetAllBooksResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Controller.ServiceReferenceBooks.GetAllBooksResponse> Controller.ServiceReferenceBooks.WebServiceBooksSoap.GetAllBooksAsync(Controller.ServiceReferenceBooks.GetAllBooksRequest request) {
            return base.Channel.GetAllBooksAsync(request);
        }
        
        public System.Threading.Tasks.Task<Controller.ServiceReferenceBooks.GetAllBooksResponse> GetAllBooksAsync() {
            Controller.ServiceReferenceBooks.GetAllBooksRequest inValue = new Controller.ServiceReferenceBooks.GetAllBooksRequest();
            inValue.Body = new Controller.ServiceReferenceBooks.GetAllBooksRequestBody();
            return ((Controller.ServiceReferenceBooks.WebServiceBooksSoap)(this)).GetAllBooksAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Controller.ServiceReferenceBooks.SearchBookResponse Controller.ServiceReferenceBooks.WebServiceBooksSoap.SearchBook(Controller.ServiceReferenceBooks.SearchBookRequest request) {
            return base.Channel.SearchBook(request);
        }
        
        public Controller.ServiceReferenceBooks.Books[] SearchBook(string booksName, int publishedYear, string publisherName) {
            Controller.ServiceReferenceBooks.SearchBookRequest inValue = new Controller.ServiceReferenceBooks.SearchBookRequest();
            inValue.Body = new Controller.ServiceReferenceBooks.SearchBookRequestBody();
            inValue.Body.booksName = booksName;
            inValue.Body.publishedYear = publishedYear;
            inValue.Body.publisherName = publisherName;
            Controller.ServiceReferenceBooks.SearchBookResponse retVal = ((Controller.ServiceReferenceBooks.WebServiceBooksSoap)(this)).SearchBook(inValue);
            return retVal.Body.SearchBookResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Controller.ServiceReferenceBooks.SearchBookResponse> Controller.ServiceReferenceBooks.WebServiceBooksSoap.SearchBookAsync(Controller.ServiceReferenceBooks.SearchBookRequest request) {
            return base.Channel.SearchBookAsync(request);
        }
        
        public System.Threading.Tasks.Task<Controller.ServiceReferenceBooks.SearchBookResponse> SearchBookAsync(string booksName, int publishedYear, string publisherName) {
            Controller.ServiceReferenceBooks.SearchBookRequest inValue = new Controller.ServiceReferenceBooks.SearchBookRequest();
            inValue.Body = new Controller.ServiceReferenceBooks.SearchBookRequestBody();
            inValue.Body.booksName = booksName;
            inValue.Body.publishedYear = publishedYear;
            inValue.Body.publisherName = publisherName;
            return ((Controller.ServiceReferenceBooks.WebServiceBooksSoap)(this)).SearchBookAsync(inValue);
        }
    }
}
