//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Controller.ServiceReferenceBorrow {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Borrow", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Borrow : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int BidField;
        
        private int UidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsbnField;
        
        private System.DateTime BorrowDateField;
        
        private System.DateTime ReturnDateField;
        
        private System.DateTime ActualReturnDateField;
        
        private decimal LateFeeField;
        
        private System.DateTime ReservedDateField;
        
        private int RidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Bid {
            get {
                return this.BidField;
            }
            set {
                if ((this.BidField.Equals(value) != true)) {
                    this.BidField = value;
                    this.RaisePropertyChanged("Bid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Uid {
            get {
                return this.UidField;
            }
            set {
                if ((this.UidField.Equals(value) != true)) {
                    this.UidField = value;
                    this.RaisePropertyChanged("Uid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Isbn {
            get {
                return this.IsbnField;
            }
            set {
                if ((object.ReferenceEquals(this.IsbnField, value) != true)) {
                    this.IsbnField = value;
                    this.RaisePropertyChanged("Isbn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime BorrowDate {
            get {
                return this.BorrowDateField;
            }
            set {
                if ((this.BorrowDateField.Equals(value) != true)) {
                    this.BorrowDateField = value;
                    this.RaisePropertyChanged("BorrowDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime ReturnDate {
            get {
                return this.ReturnDateField;
            }
            set {
                if ((this.ReturnDateField.Equals(value) != true)) {
                    this.ReturnDateField = value;
                    this.RaisePropertyChanged("ReturnDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime ActualReturnDate {
            get {
                return this.ActualReturnDateField;
            }
            set {
                if ((this.ActualReturnDateField.Equals(value) != true)) {
                    this.ActualReturnDateField = value;
                    this.RaisePropertyChanged("ActualReturnDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public decimal LateFee {
            get {
                return this.LateFeeField;
            }
            set {
                if ((this.LateFeeField.Equals(value) != true)) {
                    this.LateFeeField = value;
                    this.RaisePropertyChanged("LateFee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime ReservedDate {
            get {
                return this.ReservedDateField;
            }
            set {
                if ((this.ReservedDateField.Equals(value) != true)) {
                    this.ReservedDateField = value;
                    this.RaisePropertyChanged("ReservedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int Rid {
            get {
                return this.RidField;
            }
            set {
                if ((this.RidField.Equals(value) != true)) {
                    this.RidField = value;
                    this.RaisePropertyChanged("Rid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceBorrow.WebServiceBorrowSoap")]
    public interface WebServiceBorrowSoap {
        
        // CODEGEN: Generating message contract since element name BorrowBookListResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BorrowBookList", ReplyAction="*")]
        Controller.ServiceReferenceBorrow.BorrowBookListResponse BorrowBookList(Controller.ServiceReferenceBorrow.BorrowBookListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BorrowBookList", ReplyAction="*")]
        System.Threading.Tasks.Task<Controller.ServiceReferenceBorrow.BorrowBookListResponse> BorrowBookListAsync(Controller.ServiceReferenceBorrow.BorrowBookListRequest request);
        
        // CODEGEN: Generating message contract since element name bookIsbn from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BorrowBook", ReplyAction="*")]
        Controller.ServiceReferenceBorrow.BorrowBookResponse BorrowBook(Controller.ServiceReferenceBorrow.BorrowBookRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BorrowBook", ReplyAction="*")]
        System.Threading.Tasks.Task<Controller.ServiceReferenceBorrow.BorrowBookResponse> BorrowBookAsync(Controller.ServiceReferenceBorrow.BorrowBookRequest request);
        
        // CODEGEN: Generating message contract since element name iSbN from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReservedBook", ReplyAction="*")]
        Controller.ServiceReferenceBorrow.ReservedBookResponse ReservedBook(Controller.ServiceReferenceBorrow.ReservedBookRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReservedBook", ReplyAction="*")]
        System.Threading.Tasks.Task<Controller.ServiceReferenceBorrow.ReservedBookResponse> ReservedBookAsync(Controller.ServiceReferenceBorrow.ReservedBookRequest request);
        
        // CODEGEN: Generating message contract since element name ShowReservedBookResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowReservedBook", ReplyAction="*")]
        Controller.ServiceReferenceBorrow.ShowReservedBookResponse ShowReservedBook(Controller.ServiceReferenceBorrow.ShowReservedBookRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowReservedBook", ReplyAction="*")]
        System.Threading.Tasks.Task<Controller.ServiceReferenceBorrow.ShowReservedBookResponse> ShowReservedBookAsync(Controller.ServiceReferenceBorrow.ShowReservedBookRequest request);
        
        // CODEGEN: Generating message contract since element name bookIsbn from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteReserved", ReplyAction="*")]
        Controller.ServiceReferenceBorrow.DeleteReservedResponse DeleteReserved(Controller.ServiceReferenceBorrow.DeleteReservedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteReserved", ReplyAction="*")]
        System.Threading.Tasks.Task<Controller.ServiceReferenceBorrow.DeleteReservedResponse> DeleteReservedAsync(Controller.ServiceReferenceBorrow.DeleteReservedRequest request);
        
        // CODEGEN: Generating message contract since element name bookIsbn from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteBorrow", ReplyAction="*")]
        Controller.ServiceReferenceBorrow.DeleteBorrowResponse DeleteBorrow(Controller.ServiceReferenceBorrow.DeleteBorrowRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteBorrow", ReplyAction="*")]
        System.Threading.Tasks.Task<Controller.ServiceReferenceBorrow.DeleteBorrowResponse> DeleteBorrowAsync(Controller.ServiceReferenceBorrow.DeleteBorrowRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BorrowBookListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BorrowBookList", Namespace="http://tempuri.org/", Order=0)]
        public Controller.ServiceReferenceBorrow.BorrowBookListRequestBody Body;
        
        public BorrowBookListRequest() {
        }
        
        public BorrowBookListRequest(Controller.ServiceReferenceBorrow.BorrowBookListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class BorrowBookListRequestBody {
        
        public BorrowBookListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BorrowBookListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BorrowBookListResponse", Namespace="http://tempuri.org/", Order=0)]
        public Controller.ServiceReferenceBorrow.BorrowBookListResponseBody Body;
        
        public BorrowBookListResponse() {
        }
        
        public BorrowBookListResponse(Controller.ServiceReferenceBorrow.BorrowBookListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BorrowBookListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Controller.ServiceReferenceBorrow.Borrow[] BorrowBookListResult;
        
        public BorrowBookListResponseBody() {
        }
        
        public BorrowBookListResponseBody(Controller.ServiceReferenceBorrow.Borrow[] BorrowBookListResult) {
            this.BorrowBookListResult = BorrowBookListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BorrowBookRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BorrowBook", Namespace="http://tempuri.org/", Order=0)]
        public Controller.ServiceReferenceBorrow.BorrowBookRequestBody Body;
        
        public BorrowBookRequest() {
        }
        
        public BorrowBookRequest(Controller.ServiceReferenceBorrow.BorrowBookRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BorrowBookRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string bookIsbn;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime dateBorrowed;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime dateReturned;
        
        public BorrowBookRequestBody() {
        }
        
        public BorrowBookRequestBody(int id, string bookIsbn, System.DateTime dateBorrowed, System.DateTime dateReturned) {
            this.id = id;
            this.bookIsbn = bookIsbn;
            this.dateBorrowed = dateBorrowed;
            this.dateReturned = dateReturned;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BorrowBookResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BorrowBookResponse", Namespace="http://tempuri.org/", Order=0)]
        public Controller.ServiceReferenceBorrow.BorrowBookResponseBody Body;
        
        public BorrowBookResponse() {
        }
        
        public BorrowBookResponse(Controller.ServiceReferenceBorrow.BorrowBookResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BorrowBookResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int BorrowBookResult;
        
        public BorrowBookResponseBody() {
        }
        
        public BorrowBookResponseBody(int BorrowBookResult) {
            this.BorrowBookResult = BorrowBookResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReservedBookRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReservedBook", Namespace="http://tempuri.org/", Order=0)]
        public Controller.ServiceReferenceBorrow.ReservedBookRequestBody Body;
        
        public ReservedBookRequest() {
        }
        
        public ReservedBookRequest(Controller.ServiceReferenceBorrow.ReservedBookRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReservedBookRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string iSbN;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime bookReserved;
        
        public ReservedBookRequestBody() {
        }
        
        public ReservedBookRequestBody(int userId, string iSbN, System.DateTime bookReserved) {
            this.userId = userId;
            this.iSbN = iSbN;
            this.bookReserved = bookReserved;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReservedBookResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReservedBookResponse", Namespace="http://tempuri.org/", Order=0)]
        public Controller.ServiceReferenceBorrow.ReservedBookResponseBody Body;
        
        public ReservedBookResponse() {
        }
        
        public ReservedBookResponse(Controller.ServiceReferenceBorrow.ReservedBookResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReservedBookResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ReservedBookResult;
        
        public ReservedBookResponseBody() {
        }
        
        public ReservedBookResponseBody(int ReservedBookResult) {
            this.ReservedBookResult = ReservedBookResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowReservedBookRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowReservedBook", Namespace="http://tempuri.org/", Order=0)]
        public Controller.ServiceReferenceBorrow.ShowReservedBookRequestBody Body;
        
        public ShowReservedBookRequest() {
        }
        
        public ShowReservedBookRequest(Controller.ServiceReferenceBorrow.ShowReservedBookRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ShowReservedBookRequestBody {
        
        public ShowReservedBookRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowReservedBookResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowReservedBookResponse", Namespace="http://tempuri.org/", Order=0)]
        public Controller.ServiceReferenceBorrow.ShowReservedBookResponseBody Body;
        
        public ShowReservedBookResponse() {
        }
        
        public ShowReservedBookResponse(Controller.ServiceReferenceBorrow.ShowReservedBookResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ShowReservedBookResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Controller.ServiceReferenceBorrow.Borrow[] ShowReservedBookResult;
        
        public ShowReservedBookResponseBody() {
        }
        
        public ShowReservedBookResponseBody(Controller.ServiceReferenceBorrow.Borrow[] ShowReservedBookResult) {
            this.ShowReservedBookResult = ShowReservedBookResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteReservedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteReserved", Namespace="http://tempuri.org/", Order=0)]
        public Controller.ServiceReferenceBorrow.DeleteReservedRequestBody Body;
        
        public DeleteReservedRequest() {
        }
        
        public DeleteReservedRequest(Controller.ServiceReferenceBorrow.DeleteReservedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteReservedRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string bookIsbn;
        
        public DeleteReservedRequestBody() {
        }
        
        public DeleteReservedRequestBody(string bookIsbn) {
            this.bookIsbn = bookIsbn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteReservedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteReservedResponse", Namespace="http://tempuri.org/", Order=0)]
        public Controller.ServiceReferenceBorrow.DeleteReservedResponseBody Body;
        
        public DeleteReservedResponse() {
        }
        
        public DeleteReservedResponse(Controller.ServiceReferenceBorrow.DeleteReservedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteReservedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DeleteReservedResult;
        
        public DeleteReservedResponseBody() {
        }
        
        public DeleteReservedResponseBody(int DeleteReservedResult) {
            this.DeleteReservedResult = DeleteReservedResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteBorrowRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteBorrow", Namespace="http://tempuri.org/", Order=0)]
        public Controller.ServiceReferenceBorrow.DeleteBorrowRequestBody Body;
        
        public DeleteBorrowRequest() {
        }
        
        public DeleteBorrowRequest(Controller.ServiceReferenceBorrow.DeleteBorrowRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteBorrowRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string bookIsbn;
        
        public DeleteBorrowRequestBody() {
        }
        
        public DeleteBorrowRequestBody(string bookIsbn) {
            this.bookIsbn = bookIsbn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteBorrowResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteBorrowResponse", Namespace="http://tempuri.org/", Order=0)]
        public Controller.ServiceReferenceBorrow.DeleteBorrowResponseBody Body;
        
        public DeleteBorrowResponse() {
        }
        
        public DeleteBorrowResponse(Controller.ServiceReferenceBorrow.DeleteBorrowResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteBorrowResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DeleteBorrowResult;
        
        public DeleteBorrowResponseBody() {
        }
        
        public DeleteBorrowResponseBody(int DeleteBorrowResult) {
            this.DeleteBorrowResult = DeleteBorrowResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceBorrowSoapChannel : Controller.ServiceReferenceBorrow.WebServiceBorrowSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceBorrowSoapClient : System.ServiceModel.ClientBase<Controller.ServiceReferenceBorrow.WebServiceBorrowSoap>, Controller.ServiceReferenceBorrow.WebServiceBorrowSoap {
        
        public WebServiceBorrowSoapClient() {
        }
        
        public WebServiceBorrowSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceBorrowSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceBorrowSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceBorrowSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Controller.ServiceReferenceBorrow.BorrowBookListResponse Controller.ServiceReferenceBorrow.WebServiceBorrowSoap.BorrowBookList(Controller.ServiceReferenceBorrow.BorrowBookListRequest request) {
            return base.Channel.BorrowBookList(request);
        }
        
        public Controller.ServiceReferenceBorrow.Borrow[] BorrowBookList() {
            Controller.ServiceReferenceBorrow.BorrowBookListRequest inValue = new Controller.ServiceReferenceBorrow.BorrowBookListRequest();
            inValue.Body = new Controller.ServiceReferenceBorrow.BorrowBookListRequestBody();
            Controller.ServiceReferenceBorrow.BorrowBookListResponse retVal = ((Controller.ServiceReferenceBorrow.WebServiceBorrowSoap)(this)).BorrowBookList(inValue);
            return retVal.Body.BorrowBookListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Controller.ServiceReferenceBorrow.BorrowBookListResponse> Controller.ServiceReferenceBorrow.WebServiceBorrowSoap.BorrowBookListAsync(Controller.ServiceReferenceBorrow.BorrowBookListRequest request) {
            return base.Channel.BorrowBookListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Controller.ServiceReferenceBorrow.BorrowBookListResponse> BorrowBookListAsync() {
            Controller.ServiceReferenceBorrow.BorrowBookListRequest inValue = new Controller.ServiceReferenceBorrow.BorrowBookListRequest();
            inValue.Body = new Controller.ServiceReferenceBorrow.BorrowBookListRequestBody();
            return ((Controller.ServiceReferenceBorrow.WebServiceBorrowSoap)(this)).BorrowBookListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Controller.ServiceReferenceBorrow.BorrowBookResponse Controller.ServiceReferenceBorrow.WebServiceBorrowSoap.BorrowBook(Controller.ServiceReferenceBorrow.BorrowBookRequest request) {
            return base.Channel.BorrowBook(request);
        }
        
        public int BorrowBook(int id, string bookIsbn, System.DateTime dateBorrowed, System.DateTime dateReturned) {
            Controller.ServiceReferenceBorrow.BorrowBookRequest inValue = new Controller.ServiceReferenceBorrow.BorrowBookRequest();
            inValue.Body = new Controller.ServiceReferenceBorrow.BorrowBookRequestBody();
            inValue.Body.id = id;
            inValue.Body.bookIsbn = bookIsbn;
            inValue.Body.dateBorrowed = dateBorrowed;
            inValue.Body.dateReturned = dateReturned;
            Controller.ServiceReferenceBorrow.BorrowBookResponse retVal = ((Controller.ServiceReferenceBorrow.WebServiceBorrowSoap)(this)).BorrowBook(inValue);
            return retVal.Body.BorrowBookResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Controller.ServiceReferenceBorrow.BorrowBookResponse> Controller.ServiceReferenceBorrow.WebServiceBorrowSoap.BorrowBookAsync(Controller.ServiceReferenceBorrow.BorrowBookRequest request) {
            return base.Channel.BorrowBookAsync(request);
        }
        
        public System.Threading.Tasks.Task<Controller.ServiceReferenceBorrow.BorrowBookResponse> BorrowBookAsync(int id, string bookIsbn, System.DateTime dateBorrowed, System.DateTime dateReturned) {
            Controller.ServiceReferenceBorrow.BorrowBookRequest inValue = new Controller.ServiceReferenceBorrow.BorrowBookRequest();
            inValue.Body = new Controller.ServiceReferenceBorrow.BorrowBookRequestBody();
            inValue.Body.id = id;
            inValue.Body.bookIsbn = bookIsbn;
            inValue.Body.dateBorrowed = dateBorrowed;
            inValue.Body.dateReturned = dateReturned;
            return ((Controller.ServiceReferenceBorrow.WebServiceBorrowSoap)(this)).BorrowBookAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Controller.ServiceReferenceBorrow.ReservedBookResponse Controller.ServiceReferenceBorrow.WebServiceBorrowSoap.ReservedBook(Controller.ServiceReferenceBorrow.ReservedBookRequest request) {
            return base.Channel.ReservedBook(request);
        }
        
        public int ReservedBook(int userId, string iSbN, System.DateTime bookReserved) {
            Controller.ServiceReferenceBorrow.ReservedBookRequest inValue = new Controller.ServiceReferenceBorrow.ReservedBookRequest();
            inValue.Body = new Controller.ServiceReferenceBorrow.ReservedBookRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.iSbN = iSbN;
            inValue.Body.bookReserved = bookReserved;
            Controller.ServiceReferenceBorrow.ReservedBookResponse retVal = ((Controller.ServiceReferenceBorrow.WebServiceBorrowSoap)(this)).ReservedBook(inValue);
            return retVal.Body.ReservedBookResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Controller.ServiceReferenceBorrow.ReservedBookResponse> Controller.ServiceReferenceBorrow.WebServiceBorrowSoap.ReservedBookAsync(Controller.ServiceReferenceBorrow.ReservedBookRequest request) {
            return base.Channel.ReservedBookAsync(request);
        }
        
        public System.Threading.Tasks.Task<Controller.ServiceReferenceBorrow.ReservedBookResponse> ReservedBookAsync(int userId, string iSbN, System.DateTime bookReserved) {
            Controller.ServiceReferenceBorrow.ReservedBookRequest inValue = new Controller.ServiceReferenceBorrow.ReservedBookRequest();
            inValue.Body = new Controller.ServiceReferenceBorrow.ReservedBookRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.iSbN = iSbN;
            inValue.Body.bookReserved = bookReserved;
            return ((Controller.ServiceReferenceBorrow.WebServiceBorrowSoap)(this)).ReservedBookAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Controller.ServiceReferenceBorrow.ShowReservedBookResponse Controller.ServiceReferenceBorrow.WebServiceBorrowSoap.ShowReservedBook(Controller.ServiceReferenceBorrow.ShowReservedBookRequest request) {
            return base.Channel.ShowReservedBook(request);
        }
        
        public Controller.ServiceReferenceBorrow.Borrow[] ShowReservedBook() {
            Controller.ServiceReferenceBorrow.ShowReservedBookRequest inValue = new Controller.ServiceReferenceBorrow.ShowReservedBookRequest();
            inValue.Body = new Controller.ServiceReferenceBorrow.ShowReservedBookRequestBody();
            Controller.ServiceReferenceBorrow.ShowReservedBookResponse retVal = ((Controller.ServiceReferenceBorrow.WebServiceBorrowSoap)(this)).ShowReservedBook(inValue);
            return retVal.Body.ShowReservedBookResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Controller.ServiceReferenceBorrow.ShowReservedBookResponse> Controller.ServiceReferenceBorrow.WebServiceBorrowSoap.ShowReservedBookAsync(Controller.ServiceReferenceBorrow.ShowReservedBookRequest request) {
            return base.Channel.ShowReservedBookAsync(request);
        }
        
        public System.Threading.Tasks.Task<Controller.ServiceReferenceBorrow.ShowReservedBookResponse> ShowReservedBookAsync() {
            Controller.ServiceReferenceBorrow.ShowReservedBookRequest inValue = new Controller.ServiceReferenceBorrow.ShowReservedBookRequest();
            inValue.Body = new Controller.ServiceReferenceBorrow.ShowReservedBookRequestBody();
            return ((Controller.ServiceReferenceBorrow.WebServiceBorrowSoap)(this)).ShowReservedBookAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Controller.ServiceReferenceBorrow.DeleteReservedResponse Controller.ServiceReferenceBorrow.WebServiceBorrowSoap.DeleteReserved(Controller.ServiceReferenceBorrow.DeleteReservedRequest request) {
            return base.Channel.DeleteReserved(request);
        }
        
        public int DeleteReserved(string bookIsbn) {
            Controller.ServiceReferenceBorrow.DeleteReservedRequest inValue = new Controller.ServiceReferenceBorrow.DeleteReservedRequest();
            inValue.Body = new Controller.ServiceReferenceBorrow.DeleteReservedRequestBody();
            inValue.Body.bookIsbn = bookIsbn;
            Controller.ServiceReferenceBorrow.DeleteReservedResponse retVal = ((Controller.ServiceReferenceBorrow.WebServiceBorrowSoap)(this)).DeleteReserved(inValue);
            return retVal.Body.DeleteReservedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Controller.ServiceReferenceBorrow.DeleteReservedResponse> Controller.ServiceReferenceBorrow.WebServiceBorrowSoap.DeleteReservedAsync(Controller.ServiceReferenceBorrow.DeleteReservedRequest request) {
            return base.Channel.DeleteReservedAsync(request);
        }
        
        public System.Threading.Tasks.Task<Controller.ServiceReferenceBorrow.DeleteReservedResponse> DeleteReservedAsync(string bookIsbn) {
            Controller.ServiceReferenceBorrow.DeleteReservedRequest inValue = new Controller.ServiceReferenceBorrow.DeleteReservedRequest();
            inValue.Body = new Controller.ServiceReferenceBorrow.DeleteReservedRequestBody();
            inValue.Body.bookIsbn = bookIsbn;
            return ((Controller.ServiceReferenceBorrow.WebServiceBorrowSoap)(this)).DeleteReservedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Controller.ServiceReferenceBorrow.DeleteBorrowResponse Controller.ServiceReferenceBorrow.WebServiceBorrowSoap.DeleteBorrow(Controller.ServiceReferenceBorrow.DeleteBorrowRequest request) {
            return base.Channel.DeleteBorrow(request);
        }
        
        public int DeleteBorrow(string bookIsbn) {
            Controller.ServiceReferenceBorrow.DeleteBorrowRequest inValue = new Controller.ServiceReferenceBorrow.DeleteBorrowRequest();
            inValue.Body = new Controller.ServiceReferenceBorrow.DeleteBorrowRequestBody();
            inValue.Body.bookIsbn = bookIsbn;
            Controller.ServiceReferenceBorrow.DeleteBorrowResponse retVal = ((Controller.ServiceReferenceBorrow.WebServiceBorrowSoap)(this)).DeleteBorrow(inValue);
            return retVal.Body.DeleteBorrowResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Controller.ServiceReferenceBorrow.DeleteBorrowResponse> Controller.ServiceReferenceBorrow.WebServiceBorrowSoap.DeleteBorrowAsync(Controller.ServiceReferenceBorrow.DeleteBorrowRequest request) {
            return base.Channel.DeleteBorrowAsync(request);
        }
        
        public System.Threading.Tasks.Task<Controller.ServiceReferenceBorrow.DeleteBorrowResponse> DeleteBorrowAsync(string bookIsbn) {
            Controller.ServiceReferenceBorrow.DeleteBorrowRequest inValue = new Controller.ServiceReferenceBorrow.DeleteBorrowRequest();
            inValue.Body = new Controller.ServiceReferenceBorrow.DeleteBorrowRequestBody();
            inValue.Body.bookIsbn = bookIsbn;
            return ((Controller.ServiceReferenceBorrow.WebServiceBorrowSoap)(this)).DeleteBorrowAsync(inValue);
        }
    }
}
